version: "3.9"

services:
  public_api:
    build: .
    container_name: yszne_public_api
    ports:
      - "8001:8000"
    command: ["uvicorn", "app.main_public:app", "--host", "0.0.0.0", "--port", "8000"]

  core_api:
    build: .
    container_name: yszne_core_api
    ports:
      - "8002:8000"
    command: ["uvicorn", "app.main_core:app", "--host", "0.0.0.0", "--port", "8000"]
